better_caves.register_biome({
        highlimit = -64,
        lowlimit = -32768,
		floor_node = better_caves.mush_soil,
        floor_depth = 2,
		floor_node_chance = 1,
		floor_schematics = {"mushroom3", "mushroom5", "mushroom9", "stalk3", "stalk5"},
		floor_schematic_chance = 200,
        floor_rare_schematics = {"mushroom21", "stalk10"},
        floor_rare_schematic_chance = 30,
		floor_decoration = {better_caves.mush_grass_01, better_caves.mush_grass_02},
        floor_decoration_chance = 2,
        floor_rare_decoration = {better_caves.mush_stalks, better_caves.mush_pods, better_caves.mush_orb},
        floor_rare_decoration_chance = 25,
		ceiling_node = better_caves.mush_soil,
        ceiling_depth = 2,
		ceiling_node_chance = 1,
		ceiling_schematics = {"gills3", "gills5", "gills7", "gills9"},
		ceiling_schematic_chance = 4,
        ceiling_rare_schematics = {"gillsglow3", "gillsglow5", "gillsglow7", "gillsglow9"},
        ceiling_rare_schematic_chance = 8,
		ceiling_decoration = {better_caves.mush_gills},
        ceiling_decoration_chance = 5,
        ceiling_rare_decoration = {better_caves.mush_gills_glow, better_caves.mush_orb_vert},
        ceiling_rare_decoration_chance = 10,
        wall_node = better_caves.mush_soil,
	})
 
