local mdnm = "better_caves_mushroom"

better_caves.register_schematic(mdnm, "/schematics/bc_mushroom_3.mts", "mushroom3")
better_caves.register_schematic(mdnm, "/schematics/bc_mushroom_5.mts", "mushroom5")
better_caves.register_schematic(mdnm, "/schematics/bc_mushroom_9.mts", "mushroom9")
better_caves.register_schematic(mdnm, "/schematics/bc_mushroom_21.mts", "mushroom21")
better_caves.register_schematic(mdnm, "/schematics/bc_gills_3.mts", "gills3") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_5.mts", "gills5") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_7.mts", "gills7") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_9.mts", "gills9") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_glow_3.mts", "gillsglow3") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_glow_5.mts", "gillsglow5") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_glow_7.mts", "gillsglow7") 
better_caves.register_schematic(mdnm, "/schematics/bc_gills_glow_9.mts", "gillsglow9") 
better_caves.register_schematic(mdnm, "/schematics/bc_stalk_3.mts", "stalk3") 
better_caves.register_schematic(mdnm, "/schematics/bc_stalk_5.mts", "stalk5") 
better_caves.register_schematic(mdnm, "/schematics/bc_stalk_10.mts", "stalk10") 
better_caves.register_schematic(mdnm, "/schematics/bc_stalk_10.mts", "mushroom51")
