better_caves.register_biome({
        highlimit = -64,
        lowlimit = -32768,
        air_node = better_caves.c_air,
		floor_node = better_caves.jungle_soil,
        floor_depth = 2,
		floor_node_chance = 1,
		floor_schematics = {"mushroom3"},
		floor_schematic_chance = 1000,
        floor_rare_schematics = {"mushroom21"},
        floor_rare_schematic_chance = 30,
		floor_decoration = {better_caves.jungle_grass_01},
        floor_decoration_chance = 2,
        floor_rare_decoration = {better_caves.jungle_glow_plant},
        floor_rare_decoration_chance = 25,
		ceiling_node = better_caves.jungle_soil,
        ceiling_depth = 2,
		ceiling_node_chance = 1,
		ceiling_schematics = {"gills3"},
		ceiling_schematic_chance = 4,
        ceiling_rare_schematics = {"gillsglow3"},
        ceiling_rare_schematic_chance = 8,
		ceiling_decoration = {better_caves.jungle_grass_01},
        ceiling_decoration_chance = 5,
        ceiling_rare_decoration = {better_caves.jungle_grass_01},
        ceiling_rare_decoration_chance = 10,
        wall_node = better_caves.jungle_wall,
	})
 
